app: distinctai-serverless
service: invoice

frameworkVersion: '3'

provider:
  name: aws
  stage: prod
  runtime: python3.8
  timeout: 30
  region: eu-west-1
  memorySize: 512

functions:
  invoice:
    handler: invoice.handler 

    events:
      - http:
          path: /invoice
          method: post
